# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cakefactory' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cakefactory
  pod 'SwiftLint'
  target 'cakefactoryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'cakefactoryUITests' do
    # Pods for testing
  end

end
